spring.application.name=expensemanager
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/planner_db
spring.datasource.username=planner_app
spring.datasource.password=B00k@B1gGr3g05
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true